const NEXT_PUBLIC_ORIGIN = process.env.NEXT_PUBLIC_ORIGIN || ''
const NEXT_PUBLIC_TRICORDER_API = process.env.NEXT_PUBLIC_TRICORDER_API || ''

export const EEnv = Object.freeze({
  NEXT_PUBLIC_ORIGIN: NEXT_PUBLIC_ORIGIN.endsWith('/') ? NEXT_PUBLIC_ORIGIN.slice(0, -1) : NEXT_PUBLIC_ORIGIN,
  NEXT_PUBLIC_TRICORDER_API: NEXT_PUBLIC_TRICORDER_API.endsWith('/') ? NEXT_PUBLIC_TRICORDER_API.slice(0, -1) : NEXT_PUBLIC_TRICORDER_API,
  NEXT_PUBLIC_GOOGLE_ANALYTICS: process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS
})
